export enum Endpoint {
  BASE_RU = 'https://www.gismeteo.ru',
  BASE_EN = 'https://www.gismeteo.com',
  SEARCH = 'https://www.gismeteo.ru/mq/search/',
  TWOWEEKS = '2-weeks/',
  MONTH = 'month/',
  NOW = 'now/',
  TOMMOROW = 'tomorrow/',
}

export enum Unit {
  TEMP_C = 'unit_temperature_c',
  TEMP_F = 'unit_temperature_f',
  PRESSURE_MMHG = 'unit_pressure_mm_hg_atm',
  PRESSURE_HPA = 'unit_pressure_h_pa',
  WIND_MS = 'unit_wind_m_s',
  WIND_KMH = 'unit_wind_km_h',
}

export enum Wildcard {
  TWOWEEKS_DATE = 'div[data-stat-value*="weather"] div.widget-row-days-date div.date',
  TWOWEEKS_TMAX = 'div[data-stat-value*="weather"] div.widget-row-chart-temperature div.value div.maxt span.UNIT_TEMP',
  TWOWEEKS_TMIN = 'div[data-stat-value*="weather"] div.widget-row-chart-temperature div.value div.mint span.UNIT_TEMP',
  TWOWEEKS_TAVG = 'div[data-stat-value*="temperature-avg"] div.value span.UNIT_TEMP',
  TWOWEEKS_SUMMARY = 'div[data-stat-value*="weather"] div.widget-row-icon div.row-item div.tooltip',
  TWOWEEKS_PRESSURE = 'div[data-stat-value*="pressure"] div.widget-row-chart-pressure div.value div.maxt span.UNIT_PRESSURE',
  TWOWEEKS_WINDSPEED = 'div[data-stat-value*="wind"] div.widget-row-wind-speed div.row-item span.UNIT_WIND',
  TWOWEEKS_WINDGUST = 'div[data-stat-value*="wind"] div.widget-row-wind-gust div.row-item span.UNIT_WIND',
  TWOWEEKS_WINDDIR = 'div[data-stat-value*="wind"] div.widget-row-wind-direction div.row-item div.direction',
  TWOWEEKS_PRECIPITATION = 'div[data-stat-value*="weather"] div.widget-row-precipitation-bars div.row-item div.item-unit',
  TWOWEEKS_HUMIDITY = 'div[data-stat-value*="humidity"] div.widget-items div.row-item',
  TWOWEEKS_ROADS = 'div[data-stat-value*="roadcondition"] div.row-item div.item-description',
  TWOWEEKS_GEOMAGNETIC = 'div[data-stat-value*="geomagnetic"] div.row-item div.item',
  TWOWEEKS_POLLEN_BIRCH = 'div[data-stat-value*="pollen"] div.widget-row-pollen-birch-point div.row-item div.item',
  TWOWEEKS_POLLEN_GRASS = 'div[data-stat-value*="pollen"] div.widget-row-pollen-grass-point div.row-item div.item',
  TWOWEEKS_POLLEN_RAGWEED = 'div[data-stat-value*="pollen"] div.widget-row-pollen-ragweed div.row-item div.item',
  MONTH_DATE = 'div.widget-month div.date',
  MONTH_TMAX = 'div.widget-month div.maxt span.UNIT_TEMP',
  MONTH_TMIN = 'div.widget-month div.mint span.UNIT_TEMP',
  NOW_TEMP = 'div.now div.now-weather span.UNIT_TEMP',
  NOW_TEMPFEELS = 'div.now div.now-feel span.UNIT_TEMP',
  NOW_WINDSPEED = 'div.now div.wind div.UNIT_WIND',
  NOW_WINDDIR = 'div.now div.wind div.UNIT_WIND div.item-measure div',
  NOW_PRESSURE = `div.now div.pressure div.UNIT_PRESSURE`,
  NOW_HUMIDITY = 'div.now div.humidity div.item-value',
  NOW_SUMMARY = 'div.now div.now-desc',
  NOW_GEOMAGNETIC = 'div.now div.gm div.item-value',
  NOW_WATER = 'div.now div.water div.item-value div.UNIT_TEMP',
  NOW_SUNRISE = 'div.now div.now-astro div.now-astro-sunrise div.time',
  NOW_SUNSET = 'div.now div.now-astro div.now-astro-sunset div.time',
  TOMORROW_TIME = 'div[data-stat-value*="weather"] div.widget-row-time div.row-item',
  TOMORROW_TEMP = 'div[data-stat-value*="weather"] div.widget-row-chart-temperature div.value span.UNIT_TEMP',
  TOMORROW_PRECIPITATION = 'div[data-stat-value*="weather"] div.widget-row-precipitation-bars div.row-item div.item-unit',
  TOMORROW_SUMMARY = 'div[data-stat-value*="weather"] div.widget-row-icon div.row-item div.tooltip',
  TOMORROW_WINDSPEED = 'div[data-stat-value*="wind"] div.widget-row-wind-speed div.row-item span.UNIT_WIND',
  TOMORROW_WINDGUST = 'div[data-stat-value*="wind"] div.widget-row-wind-gust div.row-item span.UNIT_WIND',
  TOMORROW_WINDDIR = 'div[data-stat-value*="wind"] div.widget-row-wind-direction div.row-item div.direction',
  TOMORROW_POLLEN_BIRCH = 'div[data-stat-value*="pollen"] div.widget-row-pollen-birch-point div.row-item div.item',
  TOMORROW_POLLEN_GRASS = 'div[data-stat-value*="pollen"] div.widget-row-pollen-grass-point div.row-item div.item',
  TOMORROW_POLLEN_RAGWEED = 'div[data-stat-value*="pollen"] div.widget-row-pollen-ragweed div.row-item div.item',
  TOMORROW_ROADS = 'div[data-stat-value*="roadcondition"] div.row-item div.item-description',
  TOMORROW_PRESSURE = 'div[data-stat-value*="pressure"] div.widget-row-chart-pressure div.value span.UNIT_PRESSURE',
  TOMORROW_HUMIDITY = 'div[data-stat-value*="humidity"] div.widget-items div.row-item',
  TOMORROW_GEOMAGNETIC = 'div[data-stat-value*="geomagnetic"] div.row-item div.item',
}
