name: CI Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install, build and test
        run: |
          yarn
          yarn run build

      - name: Increase version
        run: yarn version

      - name: Commit package.json with new version
        uses: EndBug/add-and-commit@v9
        with:
          message: 'publish new version'

      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
